name: Test Collector
description: Uploads your JSON or JUnit files to Buildkite Test Analytics
author: https://github.com/buildkite
requirements:
  - curl
configuration:
  properties:
    api-token-env-name:
      type: string
    api-url:
      type: string
    branches:
      type: string
    debug:
      type: boolean
    exclude-branches:
      type: string
    files:
      type: string
    follow-symlinks:
      type: boolean
    format:
      enum:
        - json
        - junit
    timeout:
      type: integer
  required:
    - files
    - format
  additionalProperties: false
